export let user = {
  wallpaper: "https://source.unsplash.com/random/?vietnam,nature",
  image: "https://source.unsplash.com/random/?girl",
  name: "Lorem ipsum dolor sit",
  email: "email@gmail.com",
  bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod molestiae dignissimos similique sed accusantium quia sit laborum, sint veritatis soluta autem vero incidunt, repudiandae nihil doloremque? Mollitia officiis optio tempora?",
  storiesRated: [],
  storiesRead: [],
};
export let categories = [
  { image: "./IMG/categories/all.png", name: "All", desc: "Tất tần tật các câu chuyện về mọi chủ đề." },
  { image: "./IMG/categories/family.png", name: "Family", desc: "Gia đình." },
  { image: "./IMG/categories/kid.png", name: "Kid", desc: "Thiếu nhi." },
  { image: "./IMG/categories/education.png", name: "Education", desc: "Trường học, thầy cô và bạn bè." },
  { image: "./IMG/categories/history.png", name: "History", desc: "Lịch sử và truyền thống ở Việt Nam." },
  { image: "./IMG/categories/motivation.png", name: "Motivation", desc: "Những câu chuyện vươn lên và truyền cảm hứng trong cuộc sống." },
  { image: "./IMG/categories/world.png", name: "World", desc: "Khám phá những câu truyện cổ tích khác trên thế giới.." },
];
export let stories = [
  {
    id: "00",
    name: "Câu chuyện cây khế",
    categories: ["Kid", "Education", "Family"],
    date: "24/9/2021",
    views: 100,
    length: "2:59",
    authorName: "Sóc nhí",
    pagesNum: 20, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "01",
    name: "Công chúa Jasmine và chàng Aladdin",
    categories: ["Kid", "World"],
    date: "24/9/2021",
    views: 100,
    length: "6:03",
    authorName: "Sóc nhí",
    pagesNum: 12, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "02",
    name: "Hoa tặng cô",
    categories: ["Kid", "Education"],
    date: "24/9/2021",
    views: 100,
    length: "6:50",
    authorName: "Sóc nhí",
    pagesNum: 26, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "03",
    name: "Hồ Hoàn Kiếm",
    categories: ["Kid", "History"],
    date: "24/9/2021",
    views: 100,
    length: "5:18",
    authorName: "Sóc nhí",
    pagesNum: 18, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "04",
    name: "Hũ bạc của người cha",
    categories: ["Kid", "Education", "Motivation"],
    date: "24/9/2021",
    views: 100,
    length: "4:46",
    authorName: "Sóc nhí",
    pagesNum: 12, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "05",
    name: "Lọ Lem",
    categories: ["Kid", "World"],
    date: "24/9/2021",
    views: 100,
    length: "3:06",
    authorName: "Sóc nhí",
    pagesNum: 20, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "06",
    name: "Nàng tiên cá",
    categories: ["Kid", "World"],
    date: "24/9/2021",
    views: 100,
    length: "5:43",
    authorName: "Sóc nhí",
    pagesNum: 13, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "07",
    name: "Pinocchio",
    categories: ["Kid", "World", "Education"],
    date: "24/9/2021",
    views: 100,
    length: "5:01",
    authorName: "Sóc nhí",
    pagesNum: 16, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "08",
    name: "Thánh gióng",
    categories: ["Kid", "History"],
    date: "24/9/2021",
    views: 100,
    length: "5:42",
    authorName: "Sóc nhí",
    pagesNum: 16, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
  {
    id: "09",
    name: "Thầy giáo Nguyễn Ngọc Kí",
    categories: ["Kid", "Education", "History"],
    date: "24/9/2021",
    views: 100,
    length: "7:40",
    authorName: "Sóc nhí",
    pagesNum: 22, 
    pages: [],
    audios: [],
    avgRating: 5,
    usersRating: [
      { name: "amet harum temporibus possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 5 },
      { name: "amet harum possimus", rate: 5 },
      { name: "harum temporibus possimus", rate: 4 },
    ],
  },
];
